"""Added nodes and node locations.

Revision ID: 26786821276f
Revises: 5e2962314032
Create Date: 2025-12-17 16:04:07.514921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26786821276f'
down_revision: Union[str, Sequence[str], None] = '5e2962314032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_id'), 'chunks', ['id'], unique=False)
    op.create_table('chunk_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.String(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id', 'node_id', name='uq_chunk_node')
    )
    op.create_index(op.f('ix_chunk_locations_id'), 'chunk_locations', ['id'], unique=False)
    op.alter_column('files', 'node_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('files', 'chunk_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'chunk_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('files', 'node_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_chunk_locations_id'), table_name='chunk_locations')
    op.drop_table('chunk_locations')
    op.drop_index(op.f('ix_chunks_id'), table_name='chunks')
    op.drop_table('chunks')
    # ### end Alembic commands ###
