"""added file permissions

Revision ID: 81d30ffb6b41
Revises: 26786821276f
Create Date: 2025-12-23 14:27:11.815117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81d30ffb6b41'
down_revision: Union[str, Sequence[str], None] = '26786821276f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'user_id', name='uq_file_user_permission')
    )
    op.create_index(op.f('ix_file_permissions_id'), 'file_permissions', ['id'], unique=False)
    op.create_table('file_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_versions_file_id'), 'file_versions', ['file_id'], unique=False)
    op.create_index(op.f('ix_file_versions_id'), 'file_versions', ['id'], unique=False)
    op.add_column('chunks', sa.Column('file_version_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_chunks_file_version_id'), 'chunks', ['file_version_id'], unique=False)
    op.drop_constraint(op.f('chunks_file_id_fkey'), 'chunks', type_='foreignkey')
    op.create_foreign_key(None, 'chunks', 'file_versions', ['file_version_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chunks', 'file_id')
    op.drop_index(op.f('ix_files_chunk_id'), table_name='files')
    op.drop_constraint(op.f('files_node_id_fkey'), 'files', type_='foreignkey')
    op.drop_column('files', 'size_bytes')
    op.drop_column('files', 'chunk_id')
    op.drop_column('files', 'content_type')
    op.drop_column('files', 'node_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('node_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('files', sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('files', sa.Column('chunk_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('files', sa.Column('size_bytes', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('files_node_id_fkey'), 'files', 'nodes', ['node_id'], ['id'])
    op.create_index(op.f('ix_files_chunk_id'), 'files', ['chunk_id'], unique=False)
    op.add_column('chunks', sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.create_foreign_key(op.f('chunks_file_id_fkey'), 'chunks', 'files', ['file_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_chunks_file_version_id'), table_name='chunks')
    op.drop_column('chunks', 'file_version_id')
    op.drop_index(op.f('ix_file_versions_id'), table_name='file_versions')
    op.drop_index(op.f('ix_file_versions_file_id'), table_name='file_versions')
    op.drop_table('file_versions')
    op.drop_index(op.f('ix_file_permissions_id'), table_name='file_permissions')
    op.drop_table('file_permissions')
    # ### end Alembic commands ###
